# This workflow will
# - Build the latest version of the project in the current branch
# - Push to Amazon ECR
# - Push to ECR public
# - Trigger the webhook for automated deployment
# - Wait for 180s while the deployment is being done
# - Run the automated ZAP security scan

on:
  push:
    branches: [ staging ]
  workflow_dispatch: {}

name: Run Staging Tests

jobs:  
  deploy:
    name: Build and Push to ECR
    runs-on: [self-hosted, linux, ARM64]
    timeout-minutes: 10
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: Get short SHA
      id: sha
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
  
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Copy application.properties file
      run: cp application.properties target/application.properties

    - name: Build and Push to ECR public
      id: build-and-push
      uses: wenlianggg/ecr-public-action-arm64@ver1
      with:
        dockerfile: Dockerfile
        context: .
        create_repo: fprint-backend
        tags: |
          public.ecr.aws/g1n2x3c2/fprint-backend:staging
          public.ecr.aws/g1n2x3c2/fprint-backend:${{ steps.sha.outputs.sha7 }}

  webhook:
    name: Trigger Automated Deployment via Webhook
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [deploy]
    environment: staging
    steps:
    - name: Webhook
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL_STAGING }}
        headers: '{"repository": "cs203g2t10/foodprint"}'
        body: '{"event": "staging", "repository": "cs203g2t10/foodprint"}'
    - name: Sleep for 180 seconds
      run: sleep 180s
      shell: bash

  zap-scan:
    name: Run ZAP Scan on OpenAPI
    runs-on: ubuntu-latest
    timeout-minutes: 120
    needs: [webhook]
    environment: staging
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-api-scan@v0.1.0
      with:
        target: 'https://staging.foodprint.works/v3/api-docs'
